version: "3.2"
services:
  notification-service:
    image: notification-system/com.dpiataikin.notifications-system.notification-service/application:latest
    restart: always
    environment:
      MONGO_DATASOURCE_URL: mongo
      MONGO_DATASOURCE_PORT: 27017
      MONGO_DATASOURCE_DATABASE: mydb
      BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - 8081:8080
    networks:
      - internal

  mail-worker:
    image: notification-system/com.dpiataikin.notifications-system.mail-worker/application:latest
    restart: always
    ports:
      - "8082-8085:8080"
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 250M
        reservations:
          cpus: '0.25'
          memory: 150M
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: notification_system
      POSTGRES_USER: postgres
      POSTGRES_PASS: root
      MAILSENDER_USERNAME: ${MAILSENDER_USERNAME}
      MAILSENDER_PASSWORD: ${MAILSENDER_PASSWORD}
    networks:
      - internal

networks:
  internal:
    external: true