server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: notification-service

  data:
    mongodb:
      host: ${MONGO_DATASOURCE_URL:localhost}
      port: ${MONGO_DATASOURCE_PORT:27017}
      database: ${MONGO_DATASOURCE_DATABASE:mydb}

event:
  bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:29092}
  service-name: notification-service